CREATE TABLE books (
  book_id INT PRIMARY KEY generated by default AS identity,
  title VARCHAR(255) NOT NULL,
  publication_year INT,
  in_stock BOOLEAN DEFAULT TRUE,
  author_id INT,
  FOREIGN KEY (author_id) REFERENCES authors(author_id)
);